// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCezF4KOQauwvJ2FjOHZ30MEtJalQ8KbmI',
    appId: '1:1058816230331:web:bed68139fa8d3b3ca33a9e',
    messagingSenderId: '1058816230331',
    projectId: 'budgettackerapp',
    authDomain: 'budgettackerapp.firebaseapp.com',
    databaseURL: 'https://budgettackerapp-default-rtdb.firebaseio.com',
    storageBucket: 'budgettackerapp.appspot.com',
    measurementId: 'G-HQ317QQXKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC07XbOyvMc8hVQ_zihMBDmLYjBzeD187Q',
    appId: '1:1058816230331:android:8ea246918ebb55f9a33a9e',
    messagingSenderId: '1058816230331',
    projectId: 'budgettackerapp',
    databaseURL: 'https://budgettackerapp-default-rtdb.firebaseio.com',
    storageBucket: 'budgettackerapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKZ_XHowefKF3mstpBKHFprfyk4xbeW44',
    appId: '1:1058816230331:ios:06b9b1170557a76ba33a9e',
    messagingSenderId: '1058816230331',
    projectId: 'budgettackerapp',
    databaseURL: 'https://budgettackerapp-default-rtdb.firebaseio.com',
    storageBucket: 'budgettackerapp.appspot.com',
    iosBundleId: 'com.example.budgettracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKZ_XHowefKF3mstpBKHFprfyk4xbeW44',
    appId: '1:1058816230331:ios:06b9b1170557a76ba33a9e',
    messagingSenderId: '1058816230331',
    projectId: 'budgettackerapp',
    databaseURL: 'https://budgettackerapp-default-rtdb.firebaseio.com',
    storageBucket: 'budgettackerapp.appspot.com',
    iosBundleId: 'com.example.budgettracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCezF4KOQauwvJ2FjOHZ30MEtJalQ8KbmI',
    appId: '1:1058816230331:web:26a0b2802734ebb4a33a9e',
    messagingSenderId: '1058816230331',
    projectId: 'budgettackerapp',
    authDomain: 'budgettackerapp.firebaseapp.com',
    databaseURL: 'https://budgettackerapp-default-rtdb.firebaseio.com',
    storageBucket: 'budgettackerapp.appspot.com',
    measurementId: 'G-QSKZREYWW1',
  );
}
